### ISSUE TITLE
Workshop Prep Task

### ISSUE THREAD

**Issue by Peter-Kedron** [HEGSRR/Workshop-SDSS-2023#1]
- [x] Check list of topics for sorting question of survey
- [x] Make slide for each OSP in the sorting list
- [x] Workshop webpage and slide of all our links and publications
- [x] Draft a script for the video tour of the template
- [x] Prompts for discussion of topics, all together for small attendance or in breakout groups facilitated by Joe, Peter, and Sarah
- [x] Finalize survey contact emails
- [x] Test functionality collecting email addresses and linking survey waves

**Comment by Peter-Kedron** [comment]
@josephholler I'll get a draft of the intro and practice slides together on my flights tonight (Sunday).

**Comment by josephholler** [comment]
@Peter-Kedron : working on your slides now. Please commit if there are any changes from today

**Comment by Peter-Kedron** [comment]
@josephholler Just pushed a draft set of discussion questions oriented around and product gap and skills gap analysis. Slide are good

**Comment by josephholler** [comment]
@Peter-Kedron -- I have copied content into 2nd version of the slides using template and included a slides for survey link and data visualization. I'm curious if that works for you without installing the web view powerpoint plugin?
Also check issue #2 : I think all evaluation data collection infrastructure on Qualtrics is ready to go now.

**Comment by josephholler** [comment]
Thinking about sequence:

- start with slide for survey (3min)
- Peter's short introduction (5min)
  - leaves time for data to populate in survey and graph to render
  - While Peter is presenting, Joe will reorder the practices slides to match the graph
- Conclude one slide show with the graph of practices, which is automatically ordered by number of responses "already using" (5min)
  - Discuss commonly-accepted practices quickly to emphasize the lesser-known ones
- video presentation (10min)
- discussion (15min)

**Comment by josephholler** [comment]
done!
